### ISSUE TITLE
数据处理

### ISSUE THREAD

**Issue by haha1958** [mx54039q/FFGAN#11]
你好，我查看论文的时候发现你使用了MTCNN来对齐人脸，请问你使用的是Facenet里整理的代码吗？如果是的话，你有修改代码里的参数吗？如果修改的话。 
    minsize = 20 # minimum size of face
    threshold = [ 0.6, 0.7, 0.7 ]  # three steps's threshold
    factor = 0.709 # scale factor
方便告诉我这三个参数的值是多少呢？

**Comment by mx54039q** [comment]
具体数值已经不清楚了, 应该就是这些默认的参数, 我没有做其他的修改.

**Comment by haha1958** [comment]
> 具体数值已经不清楚了, 应该就是这些默认的参数, 我没有做其他的修改.

好的，但是我看你论文里给出的图片跟我切割出来的图片不太一样，或许你改了参数margin吗？ 
那么mtcnn切割不出的人脸你怎么处理了呢？直接抛弃了吗？我利用multipie数据集跑出来的结果跟论文里差距太大了，是因为代码里参数与论文设置参数不同吗？抱歉问了这么多问题。😀
parser.add_argument('--margin', type=int,
        help='Margin for the crop around the bounding box (height, width) in pixels.', default=44)

**Comment by mx54039q** [comment]
切割不出的人脸, 你是在测试IJBA还是MultiPIE呢? 切不出来的图是直接用的数据集官方的特征点. 效果不好的话, 你有做人脸对齐吗?

**Comment by haha1958** [comment]
我在受控条件下进行实验时，处理训练数据也就是MultiPIE数据集时，直接利用了facenet中的align_dataset_mtcnn.py程序，有些图片MTCNN剪切不出，直接没有使用。至于你所说的人脸对齐，是指人脸矫正吗？我只用了这一个程序，应该是只进行了人脸的检测和切割。你说的利用数据集官方的特征点是指利用这些特征点处理训练数据吗？也就是说你用的不仅仅是facenet中的代码还是说你使用的是MTCNN官方的代码？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Q1"<notifications@github.com&gt;; 
发送时间: 2019年11月13日(星期三) 下午5:25
收件人: "mx54039q/fnm"<fnm@noreply.github.com&gt;; 
抄送: "杜慧敏"<1483372575@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mx54039q/fnm] 数据处理 (#11)




切割不出的人脸, 你是在测试IJBA还是MultiPIE呢? 切不出来的图是直接用的数据集官方的特征点. 效果不好的话, 你有做人脸对齐吗?

**Comment by mx54039q** [comment]
1. 只用了mtcnn, 没有用facenet.
2. 人脸对齐是将人脸的特征点(比如眼睛, 鼻子)用仿射变换对齐到特定的点, 这在人脸识别中是很普遍的方法.

**Comment by haha1958** [comment]
我在https://github.com/kpzhang93/MTCNN_face_detection_alignment里没有找到仿射变换的代码，不知道是不是我看漏了哪里，论文里好像没有说明图片需要进行仿射变换对齐，如果预处理需要对齐的话，请问你是否方便提供对齐的代码？
