### ISSUE TITLE
论文数据读取问题

### ISSUE THREAD

**Issue by SkyJiashu** [mx54039q/FFGAN#13]
你好，这个想法非常有意思。但是我复现的时候发现，代码中没有用和论文一致的命名。代码里是frontal和profile两个图片输入，是否可以理解为frontal是论文补充材料里面的y，profile是论文补充材料里面的x。

y都是MultPIE的正脸图片（原文：”In constrained experiment, we separate training set of the Multi-PIE Setting-1 into non-normal set (12 poses and 20 illuminations of 150 identities) and normal set (front pose.....“）。 那在unconstrained experiment下，normal set就是frontal pose的MultiPIE了。这样理解对吗？

x都是CASIA中的图片，对应constrained experiment中12个侧脸角度图片。

谢谢！

**Comment by mx54039q** [comment]
是的。
