### ISSUE TITLE
pytorch复现

### ISSUE THREAD

**Issue by pongkun** [mx54039q/FFGAN#15]
我在用pytorch复现模型，使用的Multi-pie，但是训练了好多轮了   得到的效果很模糊，loss也很大。。请问您遇到过这种情况吗？谢谢
Loss_G: 24715.967605091395	
Loss_D: -28774.34555010077
End of epoch 10
![image](https://user-images.githubusercontent.com/21241974/74396315-95725300-4e4c-11ea-9dba-ae6f22e36429.png)

**Comment by mx54039q** [comment]
可能是损失权重的问题. 如果生成的图效果比较差, 先把perceptual loss和对抗loss关掉, 只剩下MSE. 然后再慢慢调大另外两个loss.

**Comment by pongkun** [comment]
多谢，我试试看，另外方便加个联系方式吗，嘿嘿

**Comment by mx54039q** [comment]
可以邮箱联系我
