### ISSUE TITLE
About Train

### ISSUE THREAD

**Issue by cLEARLoVE00** [mx54039q/FFGAN#19]
Hello，Author，thank you open source code！About how to train model I want to know the front list and profile list how to bulid,do you have some examples to show?

**Comment by mx54039q** [comment]
Thanks for your interest. The experiment settings (e.g. dataset construct) are listed in detail in our paper. You can get it in the Experiment Section.

**Comment by cLEARLoVE00** [comment]
I have some question，I cannot understand your paper what is normal  dataset,is front face or  profile and front face?can you tell me how to set my normal dataset?

**Comment by mx54039q** [comment]
Sec 4.1  in our paper, it is saying that "In unconstrained experiment, the non-normal face set contains 297,369 face images from unconstrained dataset CASIA-WebFace [28], while the normal face set contains 5,000 face images (front pose and 20 illuminations of 250 identities) from Multi-PIE"
