### ISSUE TITLE
可以提供vgg_face.npy吗

### ISSUE THREAD

**Issue by gyingqiang** [mx54039q/FFGAN#2]
首先感谢分享这么棒的代码
我试着跑了一下代码，生成的人物正脸照片，相比较而言epoch1的人脸照片会好一些，请问一下，你自己测试的时候，生成的正脸照片效果怎么样？
有一个细节和你的实验不一样，我用的vgg_face 的fc6特征，你可以提供你的npy文件吗

**Comment by mx54039q** [comment]
实验还在调试阶段，目前效果还可以
我用的是pool6的特征, npy文件直接用caffe zoo的二进制文件转的
多谢关注

**Comment by mx54039q** [comment]
实验还在调试阶段，目前效果还可以
我用的是pool6的特征, npy文件直接用caffe zoo的二进制文件转的
多谢关注

**Comment by hanzy88** [comment]
您好，很感谢您的分享。不知道可否分享代码中的npy文件，谢谢
