### ISSUE TITLE
Questions about Rank-1 recognition rates on Table 2

### ISSUE THREAD

**Issue by BossunWang** [mx54039q/FFGAN#21]
Hi, that's a nice work and robust model to generate  normal face.
I have question about table 2, you said "The performance gap with the other methods lies in two points: 
1) These methods ﬁne-tune the baseline (Light-CNN) on the Multi-PIE database, while our FNM is directly incorporated to face recognition model; 
2) These methods train with paired data and identity information while our FNM keeps the same training strategy with uncontrolled environment"
No matter how TP-GAN, PIM and CAPG-GAN are better than FNM on ±90◦, and their fine tune not use VGG-Face, Is  that right?
so, I don't understand why your FNM+VGG-Face is too low almost same as c-CNN and what you would like to represent on Table 2?

**Comment by mx54039q** [comment]
Sorry for the late reply. 
Make a correction, the statement you mentioned is about Table 3. And this statement is about the experiments on Multi-PIE, not on VGG-Face. 
So, the first sentence means the other methods  were trained on the trainning data on the MultiPIE,  while FNM didn't.
Hope my words helpful. Sorry again!

**Comment by BossunWang** [comment]
OK, thanks your reply.
You would like to  represent your model have robust results on unknown data.
Thanks again
