### ISSUE TITLE
LayerNorm in discriminator

### ISSUE THREAD

**Issue by ghost** [mx54039q/FFGAN#24]
Hello, Thanks for your sharing!
 Could I ask a question? In discriminator, why you use layer norm instead of batch norm? 
Thanks again.

**Comment by mx54039q** [comment]
Actually, you may use layer norm both in Generator and Discriminator, instead of batch norm. LN is a better choice for generative model due to the batchsize problem.

**Comment by ghost** [comment]
Thank you!
