### ISSUE TITLE
How to prepare dataset trainning

### ISSUE THREAD

**Issue by ThinhPham24** [mx54039q/FFGAN#26]
Hi, Thank you for your open code. Can you help me explain preparing the dataset as profile_path, profile_list, front_path, front_list in your code?.

**Comment by mx54039q** [comment]
我已收到你的邮件。                                               by    钱一琛

**Comment by mx54039q** [comment]
As it has been long for the code releasing, sorry i can't remember the detail. The 'profile_path' may represent the path to the profile face image, while the 'profile_list' is the image list of profile face. So as 'front_path' and 'front_list'.

**Comment by ThinhPham24** [comment]
Thank you so much
