### ISSUE TITLE
请问代码的网络结构是如何设计的?论文作者好像没有给参考结构啊?

### ISSUE THREAD

**Issue by Rongchangle** [mx54039q/FFGAN#3]
论文中虽然给了链接:  http://cvlab.cse.msu.edu/
project-face-frontalization.html. 但是点进去并没有发现作者给出的网络结构. 所以我想问这个代码的网络结构是你自己想出来的吗?

**Comment by mx54039q** [comment]
跟那个论文完全无关, 只是我暂时起了这个名字而已.
