### ISSUE TITLE
关于代码中的测试部分

### ISSUE THREAD

**Issue by haha1958** [mx54039q/FFGAN#4]
我发现代码有两处用到了测试test_path，我有两个问题想请教一下：
1、config.py中提到的test_path和test.py中的test_path 是同一个吗？
2、如果他们是同一个，那么我理解的是test_path中图片为不包含训练集的侧脸，如果不是同一个，他们分别指代什么呢？
谢谢！！

**Comment by mx54039q** [comment]
是同一个. tf.app.flags用作参数解析.

**Comment by haha1958** [comment]
> 是同一个. tf.app.flags用作参数解析.

**Comment by haha1958** [comment]
好的，非常感谢




------------------ 原始邮件 ------------------
发件人: "Q1"<notifications@github.com>; 
发送时间: 2019年7月2日(星期二) 晚上8:14
收件人: "mx54039q/fnm"<fnm@noreply.github.com>; 
抄送: "杜慧敏"<1483372575@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [mx54039q/fnm] 关于代码中的测试部分 (#4)




是同一个. tf.app.flags用作参数解析.
