### ISSUE TITLE
定量实验部分 

### ISSUE THREAD

**Issue by haha1958** [mx54039q/FFGAN#5]
我尝试复现你的论文，实验中使用CASIA-WebFace（no-nomal face）和Multi-Pie（normal face ）,训练3个epoch后，利用训练的模型将部分IJBA的人脸数据转正，但效果很不理想。将Multi-pie侧脸转正，感觉效果还不错。我不确定定性实验是否可信，所以请问你是否考虑上传预训练的模型，或者是定量实验的代码？谢谢！！
![112](https://user-images.githubusercontent.com/43982480/60654916-74419100-9e7f-11e9-90a6-e54e9bddae45.jpg)
![32_45_1](https://user-images.githubusercontent.com/43982480/60654930-799edb80-9e7f-11e9-88c1-7175b1c97c51.png)

**Comment by DamDam123** [comment]
你好，想问一下，你在训练的时候对mutil-PIE中俯角图像预处理进行对齐了吗？

**Comment by haha1958** [comment]
> 你好，想问一下，你在训练的时候对mutil-PIE中俯角图像预处理进行对齐了吗？

你好，论文里使用了13种角度，所以我去掉了两个俯角，没有使用这两个角度的图片

**Comment by cLEARLoVE00** [comment]
你好想问下你的test数据集用的什么，是IJB-A数据集么？
