### ISSUE TITLE
Did you align the faces in the unnormal dataset?

### ISSUE THREAD

**Issue by ilovecv** [mx54039q/FFGAN#6]
Hi,

Thank you very much for sharing the awesome work!
For the unnormal dataset, like CASIA-WEBFACE, did you apply alignment to the faces?
Could you please provide the script to preprocess the faces? Thanks!

**Comment by mx54039q** [comment]
I didn't do any alignment for unnormal face. The face pre-process is done by my teammate so i can not provide this stuff. By the way, you can do face detection and face alignment as you like. Just remenber to modify the attention region of normal face correspendingly. :)

**Comment by ilovecv** [comment]
Got it, thanks!
