### ISSUE TITLE
Could you please provide the image list of the unormal dataset?

### ISSUE THREAD

**Issue by ilovecv** [mx54039q/FFGAN#7]
Hi,

May I ask why you only used 297,369 images in CASIA-Webface instead of all the images? And I am wondering if you could provide the image list that you used so I can reproduce your results?
Thank you very much!

**Comment by mx54039q** [comment]
First, the answer is that you can use all the images in CASIA-Webface which is proved to be doable. The key limitation lies in normal face set, not unnormal face set.
As the number of 297369, I just separated the whole dataset into unfrontal and near-frontal in my early try. It's a long story. :)

**Comment by ilovecv** [comment]
Thanks!
