### ISSUE TITLE
Improvement over VGG-Face2

### ISSUE THREAD

**Issue by eladrich** [mx54039q/FFGAN#9]
Hi,
Really interesting work, a question relating to the experiments.
The paper shows an impressive boost in performance compared to Light-CNN and VGG-Face, would you still get such boost for VGG-Face2? Or is the model limited to the results of VGG-Face2 as this is the encoder used during training.

**Comment by mx54039q** [comment]
Good question. 
The truth is the same as you said "the model is limited to the results of VGG-Face2 as this is the encoder used during training".  The VGG-Face2 result on normalized faces has a degeneration. However, for set-to-set face recognition (e.g. IJB-A), we got a boost by feature fusion (as FF-GAN did). The results were not reported in the paper.

**Comment by eladrich** [comment]
Interesting, thanks
